[tool.black]
line-length = 100

[tool.scaffolding]
project = "newscaff"
project_type = "hive"
default_db_name = "{{ user }}_{{ project }}"
db_init_scripts = [
    "src/app/component/sql/create_db.sql",
    "src/app/component/sql/table_ticker.sql",
]

